/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:030a9cb4-aa52-44e4-b640-ee5130a2b7d8",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_eFNfJ5Fwb",
    "aws_user_pools_web_client_id": "1v4g0h5vr7o7eflr3lgctm7eqa",
    "oauth": {}
};


export default awsmobile;
